# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b792f3ae0decc7efcd5196ceb118ce40fb02615e1dc07a943d39d4690759254971c352da85861df4caca5622d9398d18293a2b5ad9be5d6a744206e072e98ee

test:
  secret_key_base: 4ee95ee48bb25bb8e1ceae21b65d903076b2b2f88fb12ea83bf2946100a47bb1b98f8b7f356671af3f2f984aaf59d0ae9216b4b066c0fd83d0f64939c06347ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
